global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'heart-disease-mlops'

scrape_configs:
  - job_name: 'fastapi'
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'heart-disease-prediction-api'
          environment: 'development'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
