
apiVersion: v1
kind: Service
metadata:
  name: heart-disease-api-service
  labels:
    app: heart-disease-api
spec:
  selector:
    app: heart-disease-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  type: LoadBalancer
